### ISSUE TITLE
Notification when commenting on comment.

### ISSUE THREAD

**Issue by alanaasmaa** [integrations/slack#553] opened 2018-04-24 12:37 UTC
Hi,

There is currently no option to turn on commits on comments.

I would propose options `comments:all` with addittional `comments:issues etc...`

Also i did not find another issue regarding this.

**Comment by bkeepers** [comment] 2018-04-30 16:37
Thanks for the request @alanaasmaa. I think this is a duplicate of #432, but let me know if I'm misunderstanding what you're asking for.

**Closed by bkeepers** 2018-04-30 16:37 UTC
