### ISSUE TITLE
Allow to notify on new releases with release notes

### ISSUE THREAD

**Issue by nir0s** [integrations/slack#534] opened 2018-04-17 07:54 UTC
We use Zapier to post Slack messages containing repository release notes. It would be awesome to be able to simply integrate here instead and get notified on new releases.

**Comment by bkeepers** [comment] 2018-04-17 12:30
Thanks for the request, @nir0s. This looks like a duplicate of #397. Feel free to add a 👍 reaction to that issue to voice your support.

**Closed by bkeepers** 2018-04-17 12:30 UTC
