### ISSUE TITLE
Updated GitHub on Slack Not Working

### ISSUE THREAD

**Issue by CarinaHerlina** [integrations/slack#1222] opened 2021-06-03 17:18 UTC
Hi,
I have a problem with using the updated GitHub integration with Slack. I tried many commands such as /github debug, /github help, and integrating the repo into a channel, but I keep on getting /github failed with the error "invalid_user" error. Here's the screenshot:
![SharedScreenshot](https://user-images.githubusercontent.com/55306612/120685524-c6690380-c454-11eb-8032-4ccb859a874e.jpg)
I have reinstalled the app three times, but nothing change. Can someone help me with this please? Thank you beforehand!

**Comment by amitkumariiit** [comment] 2021-06-04 04:51
Hi @CarinaHerlina  are you on the slack enterprise grid?
On Enterprise Grid, If the user upgrades the app from one workspace and not from others, they can face these errors. Please upgrade the GitHub app on all the workspaces of slack enterprise grid. This would be needed to be done by the admin of the grid.
For ref https://github.com/integrations/slack/issues/1161#issuecomment-823828708

**Comment by amitkumariiit** [comment] 2021-06-09 13:47
@CarinaHerlina are you able to run the github command successfully ?

**Comment by brianv0** [comment] 2021-06-11 19:34
There's more than a few of these issues rolling around, but this one is still open some I'm going to pile on to it.

This is broken for me. I'm on the Stanford enterprise grid, we have more than 3.5k workspaces.

`/github help` is broken for me. `/github subscribe foo/bar` is broken for me.

The "Github Enterprise App" seemed to be working against Github itself for whatever reason, so users _were_ okay if they had already configured things. Unfortunately I removed all the configurations for that as well (including configurations for other users), so I have now unnecessarily broke those users as well.

**Comment by sanjeev9160** [comment] 2021-07-08 04:57
Will be closing the issue since there are no further asks. @brianv0 Please feel free to open if the issue is not resolved. 
Thanks.

**Closed by sanjeev9160** 2021-07-08 04:57 UTC
Labels: bug

**Comment by futuresoup** [comment] 2023-05-02 16:10
@ashokirla it says it's installed in my organization settings, but the Slack Channel says to *Install GitHub App*

![Screenshot 2023-05-02 at 9 08 46 AM](https://user-images.githubusercontent.com/1459051/235723313-be4a3cd0-71cd-426c-9a35-d9da7f984371.png)
![Screenshot 2023-05-02 at 9 08 36 AM](https://user-images.githubusercontent.com/1459051/235723321-4f9a2589-7ff4-4f25-978e-9fb8c8a9ae70.png)

**Comment by Overin11** [comment] 2024-10-28 07:26
https://github.com/integrations/slack/issues/1429#issue-1304590995
