### ISSUE TITLE
Repository notifications gone after upgrading Github app in Slack

### ISSUE THREAD

**Issue by dcacenabes** [integrations/slack#1168] opened 2021-04-16 08:35 UTC
Hi,

We just updated the Github app in our Slack org following the instructions https://slack.github.com

If we run `/github subscribe list` it will tell us that we are subscribed to the repository.

We also tried running `/github unsubscribe repo` and `/github subscribe repo` right after. Still notifications are missing. I tried opening/closing dummy PRs and they are not showing up.

If we check the configuration of the Github app in slack it shows correctly the channels where the user has been added
![Screenshot 2021-04-16 at 10 33 33](https://user-images.githubusercontent.com/3796899/114996682-59e37680-9e9f-11eb-8a47-c10b0e9916f0.png)

I would like to note that this happens in the channels only. I receive notifications of PRs assigned to me correctly directly from the Github App.

**Comment by dcacenabes** [comment] 2021-04-16 15:12
I am not sure what happened, but it just started working without us doing anything.

**Comment by sushmita-m** [comment] 2021-04-16 16:30
@dcacenabes good to hear that it is working now. 
Can you log a ticket with us at https://support.github.com/.
Please share the debug details in the ticket- run `\github debug` in any of your channels where it was not working.
We would like to see what broke the notifications in the first place.

**Comment by dcacenabes** [comment] 2021-04-19 08:32
> @dcacenabes good to hear that it is working now.
> Can you log a ticket with us if you have not already logged at https://support.github.com/.
> Please share the debug details in the ticket- run `\github debug` in any of your channels where it was not working.
> We would like to see what broke the notifications in the first place.

Just provided the requested information. The ticket is "Request #1109501". Hope it helps you figure it out and fix it for other people 🙏

**Comment by emresandikci** [comment] 2021-04-20 08:53
Use `*` keyword instead of `all` keyword it starts to send push notifications for all commits, I got help via GitHub support it's helped me. Several people had similar problems because there isn't mention of the keyword change on the slack's upgrade notification. But it's mentioned on docs.

**Comment by sushmita-m** [comment] 2021-04-30 04:21
@dcacenabes this could have been a issue with the signin and could have resolved after the person who has subscribed to the repo completed the signin flow again.

I am closing this since the issue is resolved for you.. feel free to reopen this issue if you are still facing issues.

**Closed by sushmita-m** 2021-04-30 04:21 UTC
