### ISSUE TITLE
[Feature Request] Separate subscribes comments on issue and pull request

### ISSUE THREAD

**Issue by luongvo** [integrations/slack#682] opened 2018-09-11 10:14 UTC
For now, when we subscribe `comments`, slack will received comments on `issues` and `pull request` too. I want them separated and just receive comments from `issues` only

**Comment by shedokan** [comment] 2018-11-17 13:44
Looks like a duplicate of https://github.com/integrations/slack/issues/591

**Comment by izuzak** [comment] 2019-02-21 20:15
Thanks for opening this, @luongvo :bow:. As mentioned above, this seems to be a duplicate of #591 so I'm closing this in favor of that issue. Please subscribe to that issue for updates and let me know if I misunderstood anything here 🙏

**Closed by izuzak** 2019-02-21 20:15 UTC
