### ISSUE TITLE
Links to images in the repo shouldn't be unfurled as text

### ISSUE THREAD

**Issue by PranayAgarwal** [integrations/slack#654] opened 2018-08-08 00:42 UTC
Image links unfurl as weird text in channel (PNG example included). The attachment could instead have the raw image link itself (if public) and Slack would display it correctly.

![image](https://user-images.githubusercontent.com/341507/43809789-1c3ddc18-9a69-11e8-9d09-e2762f02895b.png)

**Comment by bkeepers** [comment] 2018-08-09 13:19
Thanks for the report, @PranayAgarwal. This is a duplicate of #593, so I'm going to close this in favor of that issue.

**Closed by bkeepers** 2018-08-09 13:19 UTC
