### ISSUE TITLE
PR notifications stopped working after upgrading to new Slack integration.

### ISSUE THREAD

**Issue by eelco** [integrations/slack#1177] opened 2021-04-20 08:30 UTC
We have a Slack channel set up with notifications of all pull requests with a certain label.

To achieve that, we did this:
<img width="634" alt="image" src="https://user-images.githubusercontent.com/12829/115363994-3bdd8500-a1c3-11eb-8e87-0b6781090afc.png">

Previously, this worked fine, but after upgrading from the “legacy” app to the new one, it broke. I already tried unsubscribing on subscribing again.

How do we debug / resolve this?

**Comment by eelco** [comment] 2021-04-20 08:31
Also, I think it’s a bug that it subscribes to everything even though I specified `pulls`. I only unsubscribed from the `commits` because the label filters the rest and is only applicable to PRs anyway.

**Comment by emresandikci** [comment] 2021-04-20 08:53
Use `*` keyword instead of `all` keyword it starts to send push notifications for all commits, I got help via GitHub support it's helped me. Several people had similar problems because there isn't mention of the keyword change on the slack's upgrade notification. But it's mentioned on docs.

**Comment by eelco** [comment] 2021-04-20 09:35
I’m not interested in `commit` notifications though, I’m looking for PR notifications (specifically, when they merge). It looked like this before:

<img width="465" alt="image" src="https://user-images.githubusercontent.com/12829/115373779-7b5c9f00-a1cc-11eb-818c-5929bdf4ac58.png">

**Comment by sushmita-m** [comment] 2021-04-20 11:18
@eelco please note that by default, subscribe command subscribes to `issues, pulls, commits, releases`. Note that this is true even when you specify [features] along with subscribe command. More info [here](https://github.com/integrations/slack#configuration).


If you are not interested in any features, can you do a unsubscribe [features] command.
Something like `/github unsubscribe issues commits` in your case. Thank you.

**Comment by sushmita-m** [comment] 2021-04-20 11:21
@ashokirla marked it with `feature` label.

User want to be subscribe to just pr merged events.

**Comment by eelco** [comment] 2021-04-20 11:35
Hi @sushmita-m! I appreciate the explanation and the noting of the feature request.

Unfortunately, that’s not what this issue is about.

The notification of PRs merging are **not** getting sent to our Slack channel. They worked before (with the legacy app). How do we resolve this?

**Comment by sushmita-m** [comment] 2021-04-20 11:52
Oops!! that was a long explanation.

I just verified PR merge behaviour with `+label` and I am able to get the notifications.

![Uploading Screenshot 2021-04-20 at 5.21.19 PM.png…]()

Sorry to bother you, can you do a `\github subscribe list features` and verify the the `+label:` matches with the one in your PR?

**Comment by eelco** [comment] 2021-04-20 12:21
No bother at all! Thanks for your help 🙏 

<img width="435" alt="image" src="https://user-images.githubusercontent.com/12829/115394960-a3a3c800-a1e3-11eb-8d39-cc375712e3ff.png">

Note that it *does* work for other repositories. Just the notifications from `FramerStudio` have stopped since the upgrade.

**Comment by sushmita-m** [comment] 2021-04-20 17:29
Weird that it is with only one repo under the same org! I don't see anything fishy in our logs yet!

Has the same GitHub user subscribed to all four subscriptions in the channel? Asking because while sending a notification, we do verify the access of the repo against the person whose GitHub account is used to subscribe.

Is it just the pr merge notification not working with `FramerStudio`. Can you subscribe without the label and check if the pr/any other notifications are working for this repo?

**Comment by eelco** [comment] 2021-04-20 20:26
@sushmita-m Super weird indeed! Also that only that one broke 🤔 

> Has the same GitHub user subscribed to all four subscriptions in the channel

Yes, I did.

> Is it just the pr merge notification not working with FramerStudio

Hmm, good one. I enabled issues on the repo, created and closed an issue, and created and closed another issue adding the `automerge` label on creation. Nothing shows up.

I then unsubscribed in Slack from the repo and resubscribed to everything without label filter. Created and closed an issue again. Nothing shows up.

I even re-installed the GitHub app to our Slack, unsubscribed and resubscribed and tested with an issue again. But, nada.

I then used `/github signin` to make sure my account was properly connected and tested with an issue again. Still… nothing.

I obviously can’t see the “internal” events, but we do have a webhook set up for all events too, and there everything triggers as expected. My hunch would be that it’s not the events not being sent, but something going wrong on the processing side. I don’t have access to those logs, obviously.

I would love to avoid having to install the Slack integration as our own app to get to the logs and debug this further, and I hope it can be resolved on your side.

**Comment by yskkin** [comment] 2021-04-21 02:11
Reproduced in our private repo.
We receive notifications for opening a PR, but not for merging.
Our setting is not conditioned by label.

**Comment by topaztee** [comment] 2021-04-21 10:55
+1 same issue

**Comment by chessbr** [comment] 2021-04-21 11:38
Same issue, in our case we subscribed to the whole company just for releases:

```
/github subscribe [company] releases
```

We receive just notifications from a few repos

**Comment by Nivl** [comment] 2021-04-22 18:55
Similar issue for us, we get notifications for `branches` but not for anything else (we only care for  `commits` and `pulls`).

**Comment by sushmita-m** [comment] 2021-04-26 16:10
@eelco apologies for the late reply.. we don't have any good news yet. I will be updating the support ticket you logged with us. 

For others commenting on the issue, they look like different kind of issues. Please log a separate issues on the repo to get your issues resolved.

**Comment by kymikoloco** [comment] 2021-04-27 17:37
What fixed it for us was reinstalling the New App, and signing in and resubscribing.

In some cursory tests with my IT dept, the Legacy App used the `@github` user, then installing the New App added `@github2`, but if you delete/remove the Legacy App, the only user available to invite was `@github`, but the New App listed `@github2` as the authorized user:
![image](https://user-images.githubusercontent.com/3211064/116286746-96478a00-a75d-11eb-9439-b56805c4c5fb.png)

**Comment by sushmita-m** [comment] 2021-04-28 10:46
@eelco that took a long time. We fixed the issue and hope you are receiving the notifications now.

**Comment by sushmita-m** [comment] 2021-04-28 11:01
I see that you updated the internal ticket. Thanks for your patience. I am closing this issue.

**Comment by eelco** [comment] 2021-04-28 15:58
Awesome, thank you so much!

**Comment by sushmita-m** [comment] 2021-04-30 20:28
@sjmueller I checked the logs and you are running into a permission related issue when we are processing the pr merge and closed notifications. Can you run a signin command once and check if that resolves the issue?

**Comment by sjmueller** [comment] 2021-05-06 21:58
@sushmita-m do you have any update as to why permissions are broken, and why they cannot be fixed by using the `signin` command?

**Comment by sushmita-m** [comment] 2021-05-07 11:43
@sjmueller sorry, this was not being actively tracked because of this issue being closed. I logged a internal issue in eng for this. Can you also open a new issue on the integrations repo/ or log a ticket at https://support.github.com/contact to get updates.

**Comment by sjmueller** [comment] 2021-05-08 00:02
@sushmita-m why open another issue, why not re-open this one? @eelco stated:
> The notification of PRs merging are not getting sent to our Slack channel. They worked before (with the legacy app). How do we resolve this?"

This is **exactly** what we (and other teams) are experiencing. If there is a resolution beyond your suggestion of using `signin` (didn't work), please share.

**Comment by sjmueller** [comment] 2021-05-11 17:20
Thanks @pish11010 your suggestion was very clear and fixed the problem for us!

**Closed** 2021-05-11 17:44 UTC
Labels: type:feature

**Comment by sjmueller** [comment] 2021-05-11 17:49
@sushmita-m but this issue shouldn't be closed! To be clear:
1. Everything was working perfectly with the old GitHub integration with Slack
2. We were forced to upgrade to the new GitHub integration
3. Following the upgrade path caused our integration to break, as countless others are experiencing
4. The original suggestion did not work to fix the problem
5. @pish11010 was able to discover steps to fix the problem that was introduced by upgrading

The issue here is that upgrading the GitHub Slack integration causes a permissions discrepancy that isn't automatically resolved. This ticket should remain open until someone says "We figured out the problem in the upgrade process, and other teams that upgrade will no longer experience the bug"

**Comment by sushmita-m** [comment] 2021-05-13 12:57
@sjmueller I finally figured out the problem.
We had added a new permissions to the Slack app on July, 2019.

Starting with the new Slack app release, for a better user experience we are enriching the data. For example, Users will be able to see the updated label, reviewer info in the PR open notification message. When a PR is closed/ merged, users will be able to see the status of the PR in the first notification we posted as part of the PR open.

To provide this enrichment, we need the users to be on the latest version of the Slack app on the .com side. Though we haven’t updated the Slack app on the .com side, it is required for users to be on the latest version to see all of the notifications.


Having said this, we accept that it is a bad user experience to mandate the users to update and to not inform beforehand.

1. We are working to fix this on priority. So users who are on older versions of the app are not mandated to update/ and will not have a broken experience.
2. I am working with our PM to get the documentation updated.

**Comment by sjmueller** [comment] 2021-05-13 18:40
Great job investigating @sushmita-m 👏 glad there is a better understanding of the problem. We went weeks having no idea how to fix or what went wrong, and documentation will help. You should also consider detecting older integrations, and showing a heads up message during the upgrade process: "Please make sure you've accepted any request for updated permissions on GitHub, otherwise some notifications may not work as intended."

**Comment by sushmita-m** [comment] 2021-05-17 05:59
Thanks a ton @pish11010 and @sjmueller. We have fixed this. Users will continue receiving PR merged and closed notifications irrespective of the Slack app version they are using on the GitHub.

We are working on an experience to notify the users about updating the Slack app on the GitHub.
