### ISSUE TITLE
Subscribed to whole organization, Slack only picks up commits for the master branch. 

### ISSUE THREAD

**Issue by iLemon** [integrations/slack#792] opened 2019-02-17 17:01 UTC

**Comment by justinperkins** [comment] 2019-02-21 04:27
Correction to the title of this issue: "only picks up commits to the _default_ branch"

After wrestling with this app for an hour plus and feeling pretty frustrated at how much of a step back in time this feels from the days of "legacy slack integrations", I can't heart this issue enough.

From an organizational perspective, this app does everything wrong by default.

What I want: slack messages for anything that happens to any repo (including future repos) in my organization.

How to get it:

1. Add github app to slack
2. Invite github to channel
3. Subscribe github to organization with a long list of all the things you care about, aka: `/github subscribe <org> issues pulls statuses commits deployments public releases reviews comments branches commits:all`

If you follow the README, which says that most of that is enabled by default (it's not), you will end up bald and upset like me.

**Comment by izuzak** [comment] 2019-02-21 10:18
> If you follow the README, which says that most of that is enabled by default (it's not), you will end up bald and upset like me.

Hey, @justinperkins 👋 I just tried reproducing this problem, but wasn't able to. I ran `/github subscribe <org>` in a brand new channel, and then created an issue in one of the org's repos, and a notification showed up in Slack for that issue. Closing and reopening a pull request also showed a notification. With that in mind, it seems to me that the subscription indeed is subscribed to those events by default, not just to pushes on the master branch. 

@justinperkins Could you perhaps try reproducing this again and sending the details over to support@github.com so that we can investigate?

@iLemon 👋 can you clarify what you mean by your issue (there's no body with a more detailed description so I'm not sure)? Did you expect that the subscription would be active for all branches? If so, then that's not the case and is expected+documented behavior (see https://github.com/integrations/slack#configuration).

**Comment by justinperkins** [comment] 2019-02-21 14:04
@izuzak You will not get commit notifications on branches until you explicitly tell the GitHub app you want to see them. That's the main issue here (see Issue title).

**Comment by izuzak** [comment] 2019-02-21 14:54
> @izuzak You will not get commit notifications on branches until you explicitly tell the GitHub app you want to see them. That's the main issue here (see Issue title).

@justinperkins I'm not sure I'm following. Is this being pointed out as a bug or as a feature request? If I understood what you're saying correctly, then the behavior you described is expected and documented:

https://github.com/integrations/slack#configuration

<img width="1071" alt="screenshot 2019-02-21 at 15 50 52" src="https://user-images.githubusercontent.com/38924/53177512-7e5da400-35f0-11e9-9238-0d45b6ffe3c8.png">

So, by default you get notifications for commits on the default branch. If you want to get notification on other branches, you need to subscribe for them explicitly:

<img width="1049" alt="screenshot 2019-02-21 at 15 51 38" src="https://user-images.githubusercontent.com/38924/53177586-98978200-35f0-11e9-8a74-9d3710cd6bcc.png">

**Comment by justinperkins** [comment] 2019-02-21 15:25
@izuzak This isn't my Issue, I just stumbled upon it last night when this Slack app was driving me up the wall. I guess I would call it a feature request. For subscribing to organizations. I personally find the default behavior not at all what we want.

**Comment by izuzak** [comment] 2019-02-21 19:15
> This isn't my Issue, I just stumbled upon it last night when this Slack app was driving me up the wall. I guess I would call it a feature request.

Thanks for clarifying, @justinperkins. :bow: Yeah, I understand that you didn't open this issue -- that's why I initially directed the question at @iLemon (who opened the issue) and didn't expect you to answer it. 

The question I wanted to ask you was related to what you said here:

"If you follow the README, which says that most of that is enabled by default (it's not), you will end up bald and upset like me."

As far as I can tell, that's not true. As far as I can tell, the things that are listed as enabled by default are really enabled by default. Are you able to reproduce the problem and if so -- which events are not enabled by default for you but are listed as enabled by default? Again, please feel free to followup with us via support@github.com with specific details.

> For subscribing to organizations. I personally find the default behavior not at all what we want.

What would you like the default behavior to be? Would it be to subscribe to all available events? 

Thanks again for taking the time to share feedback!

**Comment by justinperkins** [comment] 2019-02-21 20:59
> What would you like the default behavior to be?

Commit & branch notifications on all repos, present and future.

**Comment by izuzak** [comment] 2019-02-22 11:04
> Commit & branch notifications on all repos, present and future.

@justinperkins By this you mean the equivalent of subscribing only to the `commits:all` and `branches` events, as documented [here](https://github.com/integrations/slack#configuration), correct? Not to any other events?

**Comment by brunolemos** [comment] 2019-02-22 21:00
I can reproduce the issue reported by OP @iLemon when subscribing to the `facebook` organization. It only sends commits to the slack, doesn't send any issue, for example. 

It works as expected for my own organization [devhubapp](https://github.com/devhubapp), I can see issues and pull requests.

**Comment by tedivm** [comment] 2019-02-25 16:31
Wow, I didn't even know subscribing to entire orgs was possible because the "help" message that shows up doesn't show it as an option.

**Comment by izuzak** [comment] 2019-03-05 09:29
> I can reproduce the issue reported by OP @iLemon when subscribing to the `facebook` organization. It only sends commits to the slack, doesn't send any issue, for example. It's probably related to permissions not enabled.

@brunolemos I just tried subscribing to the `facebook` organization and observed other events as well, not just commits. Here's a screenshot:

<img width="885" alt="screenshot 2019-03-05 at 10 28 42" src="https://user-images.githubusercontent.com/38924/53795062-79262080-3f31-11e9-92a5-150f3310f07a.png">

Perhaps you didn't wait long enough for a non-commit event to happen? 

Also, which permissions exactly are you referring to when you say "It's probably related to permissions not enabled." and where/how are they enabled/disabled?

**Comment by redders6600** [comment] 2019-03-05 11:31
My experience (with a public channel) was that when I did `/github subscribe owner/repo` I wasn't getting notifications for most things - I didn't commit to master during that time, but did create issues, etc.

I have now manually subscribe to everything, and it's working as expected, but there was no indication that my subscription was limited.

Personally I think that at least `/github subscribe list` should tell you the scopes it's subscribed to, so it doesn't just feel like it's broken with no explanation at all.

_For me_, the expected behaviour was that by default it would subscribe to _everything_ for that repo.

**Comment by brunolemos** [comment] 2019-03-05 11:55
@izuzak I think I understood the issue now. It's because I'm expecting to receive activities from all facebook repositories, but it seems the slack integration was only installed on a couple repos (like this hvvm, which is the same one I was receiving activities from. may be the only one).

**Comment by brunolemos** [comment] 2019-03-05 16:50
@redders6600 you can use `/github subscribe list features` now

**Comment by izuzak** [comment] 2019-03-11 12:08
Thanks for confirming, @brunolemos :bow:. I'm going to close this out since we've confirmed that events which should be delivered indeed are delivered. As for expanding the set of default events -- I think that should be covered by a different issue / feature request.

> UX for this could be improved. Maybe showing that the org has enabled the integration for X repos?
> 

@brunolemos please feel free to add this feedback in related existing issues or open a new issue. 👍

**Closed by izuzak** 2019-03-11 12:08 UTC

**Comment by BashCloud** [comment] 2021-04-24 22:41
Seems like particular feature changed from `commits:all` to `commits:*`

Issue can still be marked closed, writing here for quick resolution for others.
In short, this worked for me:

`/github subscribe <org> commits:*`

**Comment by strich** [comment] 2024-11-13 10:50
This really needs to be changed - I've had to chase this down through google searching. The default should be all commits. I also don't understand where you're meant to be tutorialized that you can enable all commits from the default of only the main branch.
