### ISSUE TITLE
How to subscribe to notifications for a specific branch?

### ISSUE THREAD

**Issue by lusa** [integrations/slack#625] opened 2018-06-18 03:03 UTC
Hello, I just installed the new integration and I have some questions.

1. When I subscribe to a repository inside a Slack channel, how do I configure the subscriptions for what gets sent to that channel? 

2. More specifically, I want commits to `develop` on my repository to go to the `#develop` slack channel. I don't care about other things like issues or comments, however it would be nice to know how to configure those as well.

**Comment by gyukebox** [comment] 2018-06-25 12:12
I also want to receive notifications when pushed to branches beside `master`, such as `develop` or `features`

**Comment by justinperkins** [comment] 2018-07-13 19:29
Same issue here. We do gitflow, as I imagine a lot of people do. This app is pretty useless without being able to get notifications for *all* branches.

**Comment by justinperkins** [comment] 2018-07-17 16:11
Ok, after reading through everything and messing with the commands, I've figured out that this is what we wanted:

`/github subscribe owner/repo commits:all`

//cc @lusa

**Comment by francoalbornoz92** [comment] 2018-07-18 17:04
At my team we sometimes have big stories to develop, so we branch off our master or develop branch, and start working on that particular branch. Is it possible to get notifications for anything related to that particular branch on a specific slack channel instead of getting notified about EVERYTHING?

**Comment by mayank-mahajan-guavus** [comment] 2018-07-27 05:47
::::Need to subscribe github-url for a specific feature branch::::

I am using Slack.
I have added GutHub App.
I have already subscribed my github project.
I am able to get all the commits info for master branch.

Requirement:
I want notifications regarding commits,etc. only for a specific feature branch.

Please help here.

**Comment by wilhelmklopp** [comment] 2018-07-27 13:53
I think this is a duplicate of https://github.com/integrations/slack/issues/441

Please re-open if not :)

**Closed by wilhelmklopp** 2018-07-27 13:53 UTC

**Comment by khatchad** [comment] 2020-04-17 14:28
Not sure if I need filtering. I would like to receive commit notifications on *all* branches.

**Comment by uffou** [comment] 2020-04-18 10:59
You should have at least a two master degrees in computer science in order to activate notifications for commits :D

**Comment by Chrisissorry** [comment] 2020-05-08 08:05
What about making `commits:all` the default?

**Comment by konradstrachan** [comment] 2020-08-04 17:11
I have the opposite issue, I'd like to receive notifications for only a subset of branches. 

For example:

/github subscribe owner/repo commits:specific_branch

This doesn't appear to work currently however

**Comment by xtealer** [comment] 2021-06-26 21:05
> Ok, after reading through everything and messing with the commands, I've figured out that this is what we wanted:
> 
> `/github subscribe owner/repo commits:all`
> 
> //cc @lusa

IS not working on new repositories, got commits:all and they don't appear.

**Comment by justinperkins** [comment] 2021-06-28 14:19
> > Ok, after reading through everything and messing with the commands, I've figured out that this is what we wanted:
> > `/github subscribe owner/repo commits:all`
> > //cc @lusa
> 
> IS not working on new repositories, got `commits:all` and they don't appear.

I think you want `/github subscribe owner`.  Use `/github help` to see all available commands

**Comment by styk-tv** [comment] 2021-07-14 11:12
This works
```
/github subscribe owner commits:"*"
```

**Comment by fsinisi90** [comment] 2021-08-05 14:14
Is there a way to subscribe to multiple branches but not all? I only want "dev" and "master", for example. When I subscribe to a new one the other is removed.

**Comment by bitfede** [comment] 2021-10-01 12:11
I think "all" is deprecated in favor of *

**Comment by sardarwaseemjaved** [comment] 2022-01-27 12:04
> I think "all" is deprecated in favor of *

This worked for me

**Comment by Vaunorage** [comment] 2022-04-11 12:35
Is it possible to do something like this : /github subscribe owner commits:!staging to excluse certain branches ?

**Comment by RochaMoran** [comment] 2022-09-11 20:25
> Ok, after reading through everything and messing with the commands, I've figured out that this is what we wanted:
> 
> `/github subscribe owner/repo commits:all`
> 
> //cc @lusa

Thank You

**Comment by syedamanat** [comment] 2024-01-31 11:38
`/github subscribe owner/repo(http url) commits:* comments reviews issues pulls deployments releases` 

Does it for me.

**Comment by KimPra2989** [comment] 2024-06-18 05:48
> `/github subscribe owner/repo(http url) commits:* comments reviews issues pulls deployments releases`
> 
> Does it for me.

omg it's what I've been looking for.. thx

for more details here
[Branch filters for commit](https://github.com/integrations/slack#subscribe-to-an-organization-or-a-repository)

**Comment by AMMARESIDENTE** [comment] 2024-06-18 06:21
mx#1707

Pada Sel, 18 Jun 2024 13:49, kimpra ***@***.***> menulis:
