### ISSUE TITLE
Enable notifications on reviewer assignment for PR

### ISSUE THREAD

**Issue by cybairfly** [integrations/slack#459] opened 2018-03-15 08:51 UTC
Reviewers assigned after the submission of a PR should be notified of the updated review request so that pull requester can check the PR first before assigning a reviewer or change the reviewers later on.

**Comment by bkeepers** [comment] 2018-03-16 14:48
Thanks @cybairfly for the feedback. I agree that this would be a great feature. This is a duplicate of #382, so we'll track this there.

Thanks!

**Closed by bkeepers** 2018-03-16 14:48 UTC

**Comment by yuqil725** [comment] 2021-08-23 15:33
We are also looking for this feature, any update?
