### ISSUE TITLE
[Feature Request] Being able to not see whole description on new Pull request

### ISSUE THREAD

**Issue by Luick14** [integrations/slack#824] opened 2019-03-25 15:26 UTC
Hi guys,

Is there a way to add a command so that when a new Pull request is submitted, the chatbot only paste the title and author instead of a big part of the description? In the same way than when a PR is closed:

```
Github APP [1:42 PM]
> [my/project] Pull request submitted: #1789 My Pull request Title by TheLegend27
```

Something like `/github toggleminormessages`

I guess it would be some code change arround [here](https://github.com/integrations/slack/blob/master/lib/messages/abstract-issue.js#L23) or [here](https://github.com/integrations/slack/blob/master/lib/messages/index.js#L6)

Thanks,

**Comment by davidcelis** [comment] 2019-03-25 23:24
I think this _might_ be a duplicate of #564

**Closed** 2020-04-01 00:02 UTC
Labels: wontfix
