### ISSUE TITLE
`/github subscribe list` broken, due to "invalid_blocks"

### ISSUE THREAD

**Issue by TimWolla** [integrations/slack#1170] opened 2021-04-16 13:09 UTC
When I attempt to use `/github subscribe list features` then I'll receive a private reply from Slackbot:

> **/github** failed with the error "invalid_blocks"

**Comment by apurva1112** [comment] 2021-04-16 17:02
Hello @TimWolla, thanks for bringing this issue to our notice. We have deployed a fix for this.

Please try running the command again and let us know if you still face this error. If the error still persists, also let us know the approximate count of subscriptions you expecting in the slack channel.

**Comment by TimWolla** [comment] 2021-04-16 18:33
> Please try running the command again and let us know if you still face this error.

Unfortunately no change. I am seeing the same error message. 

> If the error still persists, also let us know the approximate count of subscriptions you expecting in the slack channel.

I would guess somewhere between 30 and 50 separate repositories within a single GitHub organization.

**Comment by apurva1112** [comment] 2021-04-19 07:21
Hello @TimWolla , 
This problem we noticed with the organizations having large number of subscriptions.  We have deployed the fix. Please check and let us know if the issue is resolved or not.

**Comment by TimWolla** [comment] 2021-04-19 07:26
> Please check and let us know if the issue is resolved or not.

I can confirm that the test I just performed worked fine.

I'll leave it up to you to close the issue, I don't know whether you still need it for any tracking purposes.

**Comment by apurva1112** [comment] 2021-04-19 07:38
> > Please check and let us know if the issue is resolved or not.
> 
> I can confirm that the test I just performed worked fine.
> 
> I'll leave it up to you to close the issue, I don't know whether you still need it for any tracking purposes.

Thanks @TimWolla  for the confirmation.

**Closed by apurva1112** 2021-04-19 07:38 UTC
