### ISSUE TITLE
Channel is unsubscribing the repository automatically whenever I commit on that repo.

### ISSUE THREAD

**Issue by samisafatli** [integrations/slack#1229] opened 2021-06-07 14:08 UTC
**Describe the bug**
The repository is being unsubscribed automatically every time I create a commit on that repo.

**To Reproduce**
1. Add GitHub App to Slack -> See the success message about the installation on the workspace
2. Go to the desired channel, type the command `/github subscribe owner/repository` 
3. Type the command `/github subscribe list` -> See the list, the repository is there ✅ 
4. Go to the project, create a commit
5. See error: There are no messages on the channel
6. Type the command `/github subscribe list` -> See the empty list, the repository is not there anymore ❌  

**Expected behavior**
I expected to receive notifications about my repo on the slack channel.

**Desktop (please complete the following information):**
 - OS: [MacOS BigSur - version 11.4]
 - Slack Version: Version 4.16.2

**Comment by amitkumariiit** [comment] 2021-06-07 14:19
@samisafatli can you please share the output of `/github debug` command on the channel where you are subscribing for debug us further ?

**Comment by samisafatli** [comment] 2021-06-07 14:40
Sure, here you go!
```
{
  "team_id": "T03M361RJ",
  "team_domain": "globo",
  "user_id": "ULYJ3N3FT",
  "channel_id": "C02389JV92B",
  "channel_name": "samitest",
  "text": "debug"
}
```

**Comment by amitkumariiit** [comment] 2021-06-09 13:34
Hi @samisafatli 
I seems like we are getting some auth error which posting the notifications to your channels and we are deleting the subscription considering the non-recoverable error.  
Can you try to update to the new version of the GitHub app ? You should be getting the reminder for that in the channel. You can follow that post on the channel to update or you can directly do it from here https://slack.github.com/
Please let me know if you see any concern.

**Comment by samisafatli** [comment] 2021-06-09 16:49
Thanks, Amir!
Actually with your answer i realized that both Github and Github Legacy were installed in the workspace. So I uninstalled the Legacy one, since he was the first one to be installed, it might override the commands to the new Github App.
Thanks, once more!

**Comment by sanjeev9160** [comment] 2021-07-07 10:17
Closing the issue. @samisafatli Please feel free to open in case the issue is not resolved. Thanks.

**Closed by sanjeev9160** 2021-07-07 10:17 UTC
Labels: bug
