### ISSUE TITLE
Heroku deployment notification nolonger work

### ISSUE THREAD

**Issue by phuongnd08** [integrations/slack#1198] opened 2021-05-01 13:35 UTC
**Describe the bug**
We used to get a notification whenever the project deployed on heroku which is gone now

**To Reproduce**
1. Go to heroku and config it to deploy master branch when ci server finished building
2. Push to github master to trigger ci server building which then trigger heroku deployment

**Expected behavior**
Receive notification about the successful deployment but doesn't receive anything

**Screenshots**
![image](https://user-images.githubusercontent.com/184037/116784111-92e53300-aabc-11eb-9599-9ff9a3550576.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Slack Desktop App
 - Version 4.15.0

**Comment by sinsoku** [comment] 2021-05-02 07:54
Duplicate of https://github.com/integrations/slack/issues/1167.

**Closed** 2021-05-03 03:04 UTC
Labels: bug
