### ISSUE TITLE
Feature arguments when subscribing to a repo are ignored

### ISSUE THREAD

**Issue by echarrod** [integrations/slack#1750] opened 2023-08-14 14:27 UTC
**Describe the bug**

Feature arguments when subscribing to a repo are ignored (but unsubscribe seems to work)

**To Reproduce**
```bash
/github subscribe luno/luno-go pulls issues
```

**Expected behavior**
```
This channel will receive notifications from [luno/luno-go](https://github.com/luno/luno-go) for:
issues, pulls
```

**Screenshots**
Actual behaviour:

![image](https://github.com/integrations/slack/assets/1381991/7750b247-69a1-47d0-bec6-1f4d7e60c21f)

**Desktop (please complete the following information):**
 - OS: iOS: Macbook Pro
 - Browser: Chrome, but this is on Slack app
 - Version 4.33.73

**Comment by rv-gbell** [comment] 2023-08-14 19:59
I am experiencing the same behavior as @echarrod

**Comment by amakhrov** [comment] 2023-08-21 19:32
Duplicate of https://github.com/integrations/slack/issues/1024 ?

**Closed** 2023-08-22 10:01 UTC
Labels: bug
