### ISSUE TITLE
Subscribe not working

### ISSUE THREAD

**Issue by theblindprophet** [integrations/slack#679] opened 2018-09-08 14:34 UTC
The Github Slack app does NOT work for my Slack workspace. I completely uninstalled the Github Slack app from my workspace an uninstalled the Slack app from my Github account.

I proceeded to reinstall both, signing with `/github signin` (which works) and when I try to subscribe to a repository (`/github subscribe https://github.com/theblindprophet/open-door-backend.git`) it always fails

 with:

> Either the app isn't installed on your repository or the repository does not exist. Install it to proceed

I have tried numerous times and it never works.

<img width="776" alt="screen shot 2018-09-08 at 10 21 53 am" src="https://user-images.githubusercontent.com/7903413/45255164-1290c300-b351-11e8-9e21-39cd58a23a04.png">
<img width="929" alt="screen shot 2018-09-08 at 10 21 58 am" src="https://user-images.githubusercontent.com/7903413/45255165-1290c300-b351-11e8-920b-9bd1035922fe.png">

**Comment by wilhelmklopp** [comment] 2018-09-10 09:30
👋 

Could you try just the following syntax:
`/github subscribe theblindprophet/open-door-backend`
or 
`/github subscribe https://github.com/theblindprophet/open-door-backend` (without the .git)

**Comment by theblindprophet** [comment] 2018-09-10 11:45
The first one appears as it if successfully subscribed. Will find out later if the notifications come through.

**Comment by sgarner** [comment] 2018-09-25 04:09
I am getting a similar error. I am using the `/github subscribe owner/repo` syntax.

Slack shows:
![image](https://user-images.githubusercontent.com/904004/45992305-30924d80-c0dd-11e8-9e94-1d24e351bab5.png)

When I click the "Install GitHub App" button, it takes me to https://github.com/marketplace/slack-github/installations/new which returns a 404 Not Found error.

Note I am not the GitHub organisation owner, but the user who is gets exactly the same thing.

**Comment by bjoernhasse** [comment] 2018-09-25 16:12
I'm seeing the exact same problem as @sgarner (and I am the organisation owner)

**Comment by esetnik** [comment] 2018-09-26 14:52
This may be a duplicate of https://github.com/integrations/slack/issues/559. We found a workaround in https://github.com/integrations/slack/issues/559#issuecomment-424722613.

**Comment by gimenete** [comment] 2018-10-01 09:36
Closing since @theblindprophet had it working and the problem that @sgarner and others had was solved on github.com

**Closed by gimenete** 2018-10-01 09:36 UTC
